spring.application.name=sagsa

spring.output.ansi.enabled=ALWAYS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.200.4.138:3306/pedro_saucedo_SAGSA?createDatabaseIfNotExist=true
spring.datasource.username=pedro_saucedo
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true